version: "3.9"
services:
  db:
    image: postgres
    container_name: hubvetdb
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
  node:
    container_name: api-node
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
    env_file:
      - .env
    ports:
      - 3080:3080
